# Generated by Django 4.2.1 on 2023-05-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_remove_quiz_user_quiz_author_competition_quiz_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
